run day:
    cargo run --release -- --day {{day}}

run-all:
    cargo run --release

debug day:
    RUST_LOG=debug cargo run -- --day {{day}}

debug-all:
    RUST_LOG=debug cargo run

build:
    cargo build --release

bench day:
    cargo bench {{day}}

bench-all:
    cargo bench